spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: {cipher}90dd618f835cc350b9395b8e60269a6916d155a36cba711878b35476f3705b71
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    password: abc123
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 300

writer:
  eeeeeeeeeeee