server:
  port: 8763
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1245495922/config-test
          search-paths: config-test
          username: 1245495922
          password: FJlt@10010
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://test:abc123@localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
    
writer: aaaaaaaaaaaa